### ISSUE TITLE
module not found... 

### ISSUE THREAD

**Issue by JensSam** [sirfoga/pygce#11]
Hi! I get the following on my Raspi when running pygce: 

```
pi@raspberrypi:~/pygce $ pygce
Traceback (most recent call last):
  File "/usr/local/bin/pygce", line 11, in <module>
    load_entry_point('pygce==2.1.2', 'console_scripts', 'pygce')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 561, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2631, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2291, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.5/dist-packages/pygce-2.1.2-py3.5.egg/pygce/cli.py", line 9, in <module>
  File "/usr/local/lib/python3.5/dist-packages/pygce-2.1.2-py3.5.egg/pygce/models/bot.py", line 19, in <module>
ImportError: No module named 'models'

```

Any idea what it might be and how to fix it?

Cheers,
Jens

**Comment by sirfoga** [comment]
You have to set the `PYTHONPATH` variable to the folder where `pygce` is located. With the [latest](https://github.com/sirfoga/pygce/commit/2ca3adc96fe5610a27497746912fd61813198e43) commit it is not more necessary: just clone the repository, run `pip install .` and run `pygce`
